# Quick test configuration for oracle evaluation with dataset data
# Uses minimal questions and dataset contexts for fast testing
# Inherits from default.yaml via main config defaults

# Base model (must match the oracle's training base)
model_name: Qwen/Qwen3-8B

# Oracle LoRA path from HuggingFace
oracle_path: adamkarvonen/checkpoints_latentqa_cls_past_lens_addition_Qwen3-8B

# Target adapter path (null = evaluate base model activations)
target_adapter_path:

# Which layer to extract activations from (as % of model depth)
layer_percent: 50

# Generation settings for oracle
max_new_tokens: 256
temperature: 0.0
do_sample: false

# Batch size for evaluation
batch_size: 8

# Token indices for activation extraction
token_start_idx: -10
token_end_idx: -2

# Repeat count (applies to segment or full_seq depending on detected input type)
repeats: 10

# Context prompts source - use dataset instead of custom
context:
  source: dataset
  # Limit for dataset source (25 samples for speed/debugging)
  n_samples: 5
