# Oracle evaluation for SFT finetuned model
# Base model (must match the oracle and the finetuned model)
model_name: google/gemma-3-1b-it

# Oracle LoRA path
oracle_path: adamkarvonen/checkpoints_cls_latentqa_past_lens_gemma-3-1b-it

# Target adapter - our SFT finetuned model
target_adapter_path: out/sft_baseline

# Which layer to extract activations from (as % of model depth)
layer_percent: 50

# Generation settings
max_new_tokens: 256
temperature: 0.0
do_sample: false

# Batch size
batch_size: 5

# Token indices for activation extraction
token_start_idx: -10
token_end_idx: 0
